region: ${lambda-proxy.region:}
endpointOverride: ${lambda-proxy.endpointOverride:}
logType: ${lambda-proxy.logType:}
functions: ${lambda-proxy.functions:}
metricsInjection: ${lambda-proxy.metricsInjection:true}
metricsName: ${lambda-proxy.metricsName:}
lambdaAppId: ${lambda-proxy.lambdaAppId:}
requestChain: ${lambda-proxy.requestChain:}
responseChain: ${lambda-proxy.responseChain:}