
# Enable JWT verification flag.
enableVerifyJwt: true

# Extract JWT scope token from the X-Scope-Token header and validate the JWT token
enableExtractScopeToken: true

# Enable JWT scope verification.
# Only valid when (enableVerifyJwt is true) AND (enableVerifyJWTScopeToken is true)
enableVerifyScope: true

# User for test only. should be always be false on official environment.
enableMockJwt: false

# For test only, should be always be true on official environment.
ignoreJwtExpiry: true

# Enable or disable JWT token logging
logJwtToken: true

# Enable or disable client_id, user_id and scope logging.
logClientUserScope: false

# Enable JWT token cache to speed up verification. This will only verify expired time
# and skip the signature verification as it takes more CPU power and long time.
enableJwtCache: true