
# ----------< Lambda Proxy Config >----------
lambda-proxy.region: ca-central-1
lambda-proxy.metricsInjection: false
lambda-proxy.enableDynamoDbCache: true

lambda-proxy.functions:
  /v1/pets@post: arn:aws:lambda:ca-central-1:442513687360:function:eadp-test-destination

lambda-proxy.requestChain:
  - "com.networknt.aws.lambda.middleware.specification.OpenApiMiddleware"
  - "com.networknt.aws.lambda.middleware.security.JwtVerifyMiddleware"
  - "com.networknt.aws.lambda.middleware.validator.ValidatorMiddleware"
  - "com.networknt.aws.lambda.middleware.header.HeaderMiddleware"
  - "com.networknt.aws.lambda.middleware.traceability.TraceabilityMiddleware"
  - "com.networknt.aws.lambda.middleware.correlation.CorrelationMiddleware"

lambda-proxy.lambdaAppId: lambda-petstore-0.0.1-SNAPSHOT
# -------------------------------------------

# ------------< Service Config >-------------
service.singletons:
#  - com.networknt.cache.CacheManager:
#      - com.networknt.aws.lambda.cache.DynamoDbCacheManager
# -------------------------------------------

# ---------< Cache Manager Config >----------
cache.caches:
  - cacheName: jwt
    expiryInMinutes: 11
    maxSize: 1000
  - cacheName: jwk
    expiryInMinutes: 600
    maxSize: 10
# -------------------------------------------

# --------< Lambda Validator Config >--------
openapi-validator.validateRequest: true
# -------------------------------------------

# --< Lambda Pooled Chain Executor Config >--
pooled-chain-executor.maxPoolSize: 10
pooled-chain-executor.corePoolSize: 10
pooled-chain-executor.keepAliveTime: 0
pooled-chain-executor.maxChainLength: 20
# -------------------------------------------

# --------< Lambda Security Config >---------
security.ignoreJwtExpiry: true
security.logJwtToken: true
security.enableJwtCache: true
# -------------------------------------------

# ----------< Lambda Header Config >---------
# header.enabled: true

# -------------------------------------------
# client.yml
client.tokenKeyServerUrl: https://networknt.oktapreview.com
client.tokenKeyUri: /oauth2/aus66u5cybTrCsbZs1d6/v1/keys
client.tokenKeyEnableHttp2: false
# client.tokenKeyAudience: dev.canada.referenceapi.networknt.oktapreview.com
