
# ----------< Lambda Proxy Config >----------
lambda-proxy.region: ca-central-1
lambda-proxy.metricsInjection: false
lambda-proxy.functions:
  /v1/pets : functionVal
lambda-proxy.requestChain:
    - "com.networknt.aws.lambda.middleware.security.SecurityMiddleware"
    - "com.networknt.aws.lambda.middleware.header.HeaderMiddleware"
    - "com.networknt.aws.lambda.middleware.traceability.TraceabilityMiddleware"
    - "com.networknt.aws.lambda.middleware.correlation.CorrelationMiddleware"
    - "com.networknt.aws.lambda.middleware.body.RequestBodyTransformerMiddleware"
lambda-proxy.lambdaAppId: arn:aws:lambda:ca-central-1:442513687360:function:eadp-light-lambda-test
# -------------------------------------------

# --< Lambda Pooled Chain Executor Config >--
pooled-chain-executor.maxPoolSize: 10
pooled-chain-executor.corePoolSize: 10
pooled-chain-executor.keepAliveTime: 0
pooled-chain-executor.maxChainLength: 20
# -------------------------------------------

# --------< Lambda Security Config >---------
security.ignoreJwtExpiry: true
security.logJwtToken: true
# -------------------------------------------

# ----------< Lambda Header Config >---------
header.requestHeader:
  - headerKey: x-traceability-id
    changeDescriptor:
      changeType: APPEND
      value: "-append-test"
  - headerKey: x-added-header
    changeDescriptor:
      changeType: ADD
      value: "addedHeaderValue"
  - headerKey: x-traceability-id
    changeDescriptor:
      changeType: PREPEND
      value: "prepend-test-"
  - headerKey: x-some-random-header
    changeDescriptor:
      changeType: REMOVE
      value: ""
# -------------------------------------------



